lanche = ('Hamburger', 'Suco', 'Pizza', 'Pudim')
#print(lanche)
#print(lanche[1:3])
print(lanche[-1:-2])
for cont in range(0, len(lanche)):
    print(lanche[cont], f"Na posicao {cont}")
print("-" * 30)
print("-" * 30)
for comida in lanche:
    print(f"eu vou comer {comida}")
print("Comi demais")
print("-" * 30)
print("-" * 30)
for pos, comida in enumerate(lanche):
    print(f"eu vou comer {comida}, na posicao {pos}")
print("-" * 30)
print("-" * 30)
print(sorted(lanche))
print("-" * 30)
print("-" * 30)
a = (2,4,6)
b = (1,3,5,7)
c = a + b
print(c)
print("-" * 30)
print("-" * 30)
print(c.count(4))
print("-" * 30)
print("-" * 30)
print(c.index(5))
